export const medicalServicesButton = [
    { name: "Акушер-гинеколог", ref: "/services/ginekolog" },
    { name: "Аллерголог-иммунолог", ref: "/services/allergolog-immunolog" },
    { name: "Гастроэнтеролог", ref: "/services/gastroenterolog" },
    { name: "Дерматолог", ref: "/services/dermatolog" },
    { name: "Кардиолог", ref: "/services/kardiolog" },
    { name: "Колопроктолог", ref: "/services/koloproktolog" },
    { name: "Массаж", ref: "/services/massage" },
    { name: "Невролог", ref: "/services/nevrolog" },
    { name: "Онколог", ref: "/services/onkolog" },
    { name: "Оториноларинголог (ЛОР)", ref: "/services/otorinolaringolog" },
    { name: "Процедурный кабинет", ref: "/services/proczedurnyij-kabinet" },
    { name: "Психолог", ref: "/services/psikholog" },
    { name: "Пульмонолог", ref: "/services/pulmonolog" },
    { name: "Ревматолог", ref: "/services/revmatolog" },
    { name: "Сердечно-сосудистый хирург", ref: "/services/serdechno-sosudistiy-hirurg" },
    { name: "Терапевт", ref: "/services/terapevt" },
    { name: "Травматолог-ортопед", ref: "/services/travmatolog-ortoped" },
    { name: "Ультразвуковая диагностика (УЗИ)", ref: "/services/ultrazvukovaya-diagnostika" },
    { name: "Уролог", ref: "/services/urolog" },
    { name: "Физиотерапия", ref: "/services/fizioterapiya" },
    { name: "Функциональная диагностика", ref: "/services/funkczionalnaya-diagnostika" },
    { name: "Хирург", ref: "/services/xirurg" },
    { name: "Эндокринолог", ref: "/services/endokrinolog" },
    { name: "Прочие услуги", ref: "/services/prochie-uslugi" },
];